SELECT * FROM public.dev_table
ALTER TABLE dev_table ADD COLUMN mssv VARCHAR(255);
ALTER TABLE dev_table ADD COLUMN hoten VARCHAR(255);
ALTER TABLE dev_table ADD COLUMN diachi VARCHAR(255);
ALTER TABLE dev_table ADD COLUMN email VARCHAR(255);
ALTER TABLE dev_table ADD COLUMN sodienthoai VARCHAR(255);
ALTER TABLE dev_table ALTER COLUMN mssv TYPE VARCHAR;
DELETE FROM dev_table
WHERE mssv IS NULL OR hoten IS NULL OR diachi IS NULL OR email IS NULL;

